# Generated by Django 4.2.1 on 2023-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence_management',
            name='Att_Date',
            field=models.DateField(null=True),
        ),
    ]
