# Generated by Django 4.2.1 on 2023-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0002_attendence_management_att_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence_management',
            name='Att_Subject',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
