# Generated by Django 4.2 on 2023-05-31 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_student_management_subject'),
        ('facultyapp', '0003_attendence_management_att_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence_management',
            name='Student_Foregin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.student_management'),
        ),
        migrations.AlterField(
            model_name='attendence_management',
            name='Att_Status',
            field=models.TextField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20),
        ),
    ]
