# Generated by Django 4.2 on 2023-06-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0006_alter_attendence_management_att_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_management',
            name='Att_Status',
            field=models.BooleanField(default=False),
        ),
    ]
