# Generated by Django 4.2 on 2023-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0009_attendence_management_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence_management',
            name='Att_Status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendence_management',
            name='Student_Status',
            field=models.TextField(default='present', null=True),
        ),
    ]
