# Generated by Django 4.2 on 2023-06-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0010_alter_attendence_management_att_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_details',
            fields=[
                ('Assignment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Assignment_Name', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'assignment_model',
            },
        ),
    ]
