# Generated by Django 4.2 on 2023-06-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0011_assignment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_details',
            name='Assignment_Branch',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment_details',
            name='Assignment_Sem',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
